baseURL = "https://adlion-gofore.github.io/test_pipeline/"
locale = "en-us"
title = "Avant UDS Library"

publishDir = "../../../_site"

[outputFormats.VersionManifest]
  mediaType      = "application/json"
  baseName       = "new-version"
  isPlainText    = true
  notAlternative = true

[outputs]
  home = ["HTML", "VersionManifest"]

[markup.highlight]
  noClasses = false

[module]
  [[module.imports]]
    path = "gitlab.com/natitec_public/bora"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "../../../docs"
    target = "content/docs"
